stages:
  - test

test:
  stage: test
  image: python:3
  script:
    - pip install coverage django
    - cd django_events
    - export SECRET_KEY=aSecretkeyaSecretkeyaSecretkeyaSecretkeyaSecretkey
    - coverage run manage.py test
    - coverage report
