stages:
  - test

test:
  stage: test
  image: python:3
  script:
    - export SECRET_KEY=aSecretkeyaSecretkeyaSecretkeyaSecretkeyaSecretkey
    - export DEBUG=0
    - export ALLOWED_HOSTS=*
    - cd django_events
    - pip install -r test-requirements.txt
    - coverage run manage.py test
    - coverage report
